-- V1__Create_Tabela_Usuario.sql


CREATE TABLE IF NOT EXISTS USUARIO (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    setor VARCHAR(255) NOT NULL,
    cargo VARCHAR(255) NOT NULL
);